# Generated by Django 5.1.6 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='operator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='operator_pd_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
