# Generated by Django 5.1.6 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0001_initial'),
    ]

    operations = [
        # Removed duplicate field additions as these fields already exist
    ] 