# Generated by Django 5.1.6 on 2025-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='secondary_photo',
            field=models.ImageField(blank=True, null=True, upload_to='secondary_photos/'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
