# Generated by Django 5.1.5 on 2025-01-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ENFORCER', 'Traffic Enforcer'), ('SUPERVISOR', 'Supervisor'), ('TREASURER', 'Treasurer'), ('CLERK', 'Office Clerk'), ('USER', 'Regular User')], default='USER', max_length=20),
        ),
    ]
