# Generated by Django 5.1.6 on 2025-03-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0002_violation_secondary_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorapplication',
            name='mayors_permit',
            field=models.FileField(blank=True, null=True, upload_to='mayors_permits/'),
        ),
    ]
