# Generated by Django 5.1.6 on 2025-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0002_add_operator_name_fields'),
    ]

    operations = [
    ]
