# Generated by Django 5.1.6 on 2025-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0003_add_operator_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='potpot_number',
            field=models.CharField(blank=True, help_text='Potpot identification number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='new_pd_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Jeepney', 'Jeepney'), ('Tricycle', 'Tricycle'), ('Potpot', 'Potpot'), ('Other', 'Other')], default='Tricycle', max_length=100),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle_type',
            field=models.CharField(choices=[('Jeepney', 'Jeepney'), ('Tricycle', 'Tricycle'), ('Potpot', 'Potpot'), ('Other', 'Other')], default='Tricycle', max_length=100),
        ),
    ]
