# Generated by Django 5.1.6 on 2025-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0004_vehicle_potpot_number_alter_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
