# Generated by Django 5.1.6 on 2025-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0006_activitylog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorapplication',
            name='barangay_certificate',
            field=models.FileField(blank=True, help_text='Barangay certificate', null=True, upload_to='barangay_certificate/'),
        ),
        migrations.AddField(
            model_name='operatorapplication',
            name='cedula',
            field=models.FileField(blank=True, help_text='Community Tax Certificate (Cedula)', null=True, upload_to='cedula/'),
        ),
        migrations.AddField(
            model_name='operatorapplication',
            name='cenro_tickets',
            field=models.FileField(blank=True, help_text='CENRO permits/tickets', null=True, upload_to='cenro_tickets/'),
        ),
        migrations.AddField(
            model_name='operatorapplication',
            name='police_clearance',
            field=models.FileField(blank=True, help_text='Police clearance certificate', null=True, upload_to='police_clearance/'),
        ),
    ]
