# Generated by Django 5.1.6 on 2025-04-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0007_operatorapplication_barangay_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='rich_content',
        ),
    ]
