# Generated by Django 5.1.6 on 2025-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0008_remove_announcement_rich_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='popup_interval',
            field=models.PositiveIntegerField(default=0, help_text='Days between popup appearances (0 = show once per session)'),
        ),
    ]
