# Generated by Django 5.1.6 on 2025-04-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0009_announcement_popup_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='popup_interval',
            field=models.IntegerField(default=0, help_text='Interval in seconds between showing this popup again to the same user'),
        ),
    ]
