# Generated by Django 5.1.6 on 2025-04-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0010_alter_announcement_popup_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='popup_interval',
        ),
    ]
