# Generated by Django 5.1.6 on 2025-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0011_remove_announcement_popup_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='capacity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
