# Generated by Django 5.1.6 on 2025-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0012_vehicleregistration_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
