# Generated by Django 5.1.6 on 2025-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_violation_system', '0013_vehicle_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='classification',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Public', 'Public'), ('Government', 'Government'), ('Commercial', 'Commercial')], max_length=20, null=True),
        ),
    ]
