# Generated by Django 5.1.6 on 2025-04-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
    ]
