# Generated by Django 5.1.6 on 2025-04-06 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0002_auto_20250406_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalcategory',
            options={'ordering': ['title'], 'verbose_name_plural': 'Educational Categories'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_accessed']},
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='completed_date',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='educationalcategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='educationalcategory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='educational.educationaltopic'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
