# Generated by Django 5.1.6 on 2025-04-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_alter_educationalcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_accessed'], 'verbose_name_plural': 'User Progress'},
        ),
    ]
