# Generated by Django 5.1.6 on 2025-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_alter_userprogress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalcategory',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Educational Categories'},
        ),
        migrations.AddField(
            model_name='educationalcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
