# Generated by Django 5.1.6 on 2025-04-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0006_quiz_quizquestion_quizanswer_userquizattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='educational/questions/'),
        ),
    ]
