# Generated by Django 5.1.6 on 2025-04-13 05:45

import traffic_violation_system.educational.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0007_alter_quizquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=traffic_violation_system.educational.models.question_image_path),
        ),
    ]
